version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run:
          name: Creating Dummy Artifacts
          command: |
            echo "my artifact file" > /tmp/art-1;
            mkdir /tmp/artifacts;
            echo "my artifact files in a dir" > /tmp/artifacts/art-2;
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - run:
          name: Install dependencies
          command: mvn -U clean install
      - store_artifacts:
          path: /tmp/art-1
          destination: artifact-file
      - store_artifacts:
          path: /tmp/artifacts
      - run:
          name: Test
          command: mvn test
workflows:
  sample: 
    jobs:
      - build-and-test
