version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - run:
          name: Install dependencies
          command: mvn -U clean install
      - run:
          name: Test
          command: mvn test

      - name: Save artifacts
        uses: actions/upload-artifact@v2
        with:
          name: maven-artifacts
          path: target/
workflows:
  sample: 
    jobs:
      - build-and-test
